# Generated by Django 4.2.17 on 2026-01-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exercises/'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workout_plans/'),
        ),
    ]
